SectionVerb {
    Value {
        TQ "HiFi"
    }
}

SectionDevice."Speaker" {
    Comment "PI AI MIC Speaker"

    Value {
        PlaybackPriority 100
        PlaybackPCM "hw:HAT,1"
        PlaybackChannels 2
    }
}

SectionDevice."Mic" {
    Comment "PI AI MIC Microphone"

    Value {
        CapturePriority 100
        CapturePCM "hw:HAT,0"
        CaptureChannels 2
    }
}
