// Copyright 2022-2023 XMOS LIMITED.
// This Software is subject to the terms of the XCORE VocalFusion Licence.


// This file contains the framework for SHF including plumbing in and out of i2s/audio,
// the cross tile link for forwarding samples to and from PP and the fork and join
// constructs for parallelising the execution of the algorithm.

#include "xcore/chanend.h"
#define DEBUG_UNIT SHF_WRAPPER
#ifndef DEBUG_PRINT_ENABLE_SHF_WRAPPER
    #define DEBUG_PRINT_ENABLE_SHF_WRAPPER 0
#endif

#ifndef FIXED_BEAMS_ENABLED
#define FIXED_BEAMS_ENABLED 0
#endif

#ifndef PI_AI_MIC_PROCESSED_USB_GAIN_Q8
#define PI_AI_MIC_PROCESSED_USB_GAIN_Q8 256
#endif

#include "debug_print.h"

#include "shf_wrapper.h"

#include <stdint.h>
#include <stdbool.h>
#include <math.h>
#include <xcore/hwtimer.h>
#include <xcore/interrupt_wrappers.h>
#include <xcore/interrupt.h>
#include <xcore/triggerable.h>
#include "xcore/channel.h"
#include <string.h>

#include "app_conf.h"
#include "shf.h"
#include "shf_init.h"
#include "shf_bypass/shf_bypass.h"
#include "tile_common.h"
#include "shf_defaults.h"
#include "packet_queue.h"
#include "aec_cmds.h" // Autogenerated
#include "pp_cmds.h" // Autogenerated
#include "doa_smoothing.h"
#include "fixed_beam_gating.h"
#if PI_AI_MIC_BOARD
#include "user_config/pi_ai_mic_hw.h"
#endif
#if PI_AI_MIC_DOA_NEOPIXEL_ENABLE
#include "user_config/pi_ai_mic_neopixel.h"
#endif
DECLARE_INTERRUPT_CALLBACK(ep0_setup_pkt_recv_isr, app_data);

/* *************************
 * Macros
 * *************************/

#define DEBUG_PRINT_WORKER_BURN_THREADS     0   //Print progress of the SHF worker threads or not

#define DUMMY_WAIT_PERCENTAGE       98.9f   // The amount of time the busy wait test task keeps running as a proportiuon of frame frequency
#define AEC_DUMMY_WAIT_TICKS        (uint32_t)((float)SHF_FRAME_TIME_TICKS * DUMMY_WAIT_PERCENTAGE / 100.0)
#define PP_DUMMY_WAIT_TICKS         (uint32_t)((float)SHF_FRAME_TIME_TICKS * DUMMY_WAIT_PERCENTAGE / 100.0)

#define SETSR(c)                asm volatile("setsr %0" : : "n"(c));
#define SET_HIGH_PRIORITY()     SETSR(XS1_SR_QUEUE_MASK)    // Force the xcore to schedule once every 5 processor clocks
#define SET_FAST_MODE()         SETSR(XS1_SR_FAST_MASK)     // Force the xcore to schedule even if blocked on event
#define TIME_AFTER(A, B) ((int)((B) - (A)) < 0)

#if PI_AI_MIC_DOA_NEOPIXEL_ENABLE
#define PI_AI_MIC_DOA_RING_JUMP_RAD          0.0872665f
#define PI_AI_MIC_DOA_RING_STABLE_FRAMES     15
#define PI_AI_MIC_TWO_PI                     (2.0f * (float)M_PI)
#ifndef PI_AI_MIC_DOA_RAW_RING_ENABLE
#define PI_AI_MIC_DOA_RAW_RING_ENABLE        1
#endif
#ifndef PI_AI_MIC_DOA_RING_OFFSET_180
#define PI_AI_MIC_DOA_RING_OFFSET_180        0
#endif
#if PI_AI_MIC_DOA_RAW_RING_ENABLE || PI_AI_MIC_RUNTIME_GEOMETRY_PROFILE_ENABLE
#define PI_AI_MIC_DOA_RAW_RING_CODE_ENABLE   1
#else
#define PI_AI_MIC_DOA_RAW_RING_CODE_ENABLE   0
#endif
#define PI_AI_MIC_RAW_DOA_SPEED_OF_SOUND     343.0f
#define PI_AI_MIC_RAW_DOA_MAX_LAG_SAMPLES    8
#define PI_AI_MIC_RAW_DOA_MIN_RMS            0.0f
#define PI_AI_MIC_RAW_DOA_MIN_CONFIDENCE     0.0f
#define PI_AI_MIC_RAW_DOA_MAX_FIT_ERROR_S    1.0f

static float pi_ai_mic_angle_delta_abs(float a, float b)
{
    float delta = fmodf(a - b + (float)M_PI, PI_AI_MIC_TWO_PI);
    if (delta < 0.0f) {
        delta += PI_AI_MIC_TWO_PI;
    }
    delta -= (float)M_PI;
    return fabsf(delta);
}

static int pi_ai_mic_doa_ring_required_stable_frames(float current_azimuth,
                                                     float candidate_azimuth)
{
#if PI_AI_MIC_RUNTIME_GEOMETRY_PROFILE_ENABLE
    if (pi_ai_mic_doa_opposite_filter_enabled() &&
        isfinite(current_azimuth) && isfinite(candidate_azimuth)) {
        float delta = pi_ai_mic_angle_delta_abs(candidate_azimuth, current_azimuth);
        float opposite_error = fabsf((float)M_PI - delta);
        if (opposite_error <= PI_AI_MIC_DOA_RING_OPPOSITE_WINDOW_RAD) {
            return pi_ai_mic_doa_opposite_stable_frames();
        }
    }
#elif PI_AI_MIC_DOA_RING_OPPOSITE_FILTER_ENABLE
    if (isfinite(current_azimuth) && isfinite(candidate_azimuth)) {
        float delta = pi_ai_mic_angle_delta_abs(candidate_azimuth, current_azimuth);
        float opposite_error = fabsf((float)M_PI - delta);
        if (opposite_error <= PI_AI_MIC_DOA_RING_OPPOSITE_WINDOW_RAD) {
            return PI_AI_MIC_DOA_RING_OPPOSITE_STABLE_FRAMES;
        }
    }
#else
    (void) current_azimuth;
    (void) candidate_azimuth;
#endif

    return PI_AI_MIC_DOA_RING_STABLE_FRAMES;
}

static float pi_ai_mic_doa_ring_select(float smoothed_azimuth, float raw_auto_azimuth)
{
    static float ring_azimuth = NAN;
    static float candidate_azimuth = NAN;
    static int candidate_count = 0;

    if (isfinite(smoothed_azimuth)) {
        ring_azimuth = smoothed_azimuth;
        candidate_azimuth = NAN;
        candidate_count = 0;
        return ring_azimuth;
    }

    if (!isfinite(raw_auto_azimuth)) {
        return ring_azimuth;
    }

    if (!isfinite(ring_azimuth) ||
        pi_ai_mic_angle_delta_abs(raw_auto_azimuth, ring_azimuth) <= PI_AI_MIC_DOA_RING_JUMP_RAD) {
        ring_azimuth = raw_auto_azimuth;
        candidate_azimuth = NAN;
        candidate_count = 0;
        return ring_azimuth;
    }

    if (!isfinite(candidate_azimuth) ||
        pi_ai_mic_angle_delta_abs(raw_auto_azimuth, candidate_azimuth) > PI_AI_MIC_DOA_RING_JUMP_RAD) {
        candidate_azimuth = raw_auto_azimuth;
        candidate_count = 1;
    } else {
        int required_stable_frames =
            pi_ai_mic_doa_ring_required_stable_frames(ring_azimuth, candidate_azimuth);
        if (candidate_count < required_stable_frames) {
            candidate_count++;
        }
    }

    int required_stable_frames =
        pi_ai_mic_doa_ring_required_stable_frames(ring_azimuth, candidate_azimuth);
    if (candidate_count >= required_stable_frames) {
        ring_azimuth = candidate_azimuth;
        candidate_azimuth = NAN;
        candidate_count = 0;
    }

    return ring_azimuth;
}

static float pi_ai_mic_doa_apply_ring_offset(float azimuth)
{
#if PI_AI_MIC_RUNTIME_GEOMETRY_PROFILE_ENABLE
    if (pi_ai_mic_doa_ring_offset_180() && isfinite(azimuth)) {
        azimuth = fmodf(azimuth + (float)M_PI, PI_AI_MIC_TWO_PI);
        if (azimuth < 0.0f) {
            azimuth += PI_AI_MIC_TWO_PI;
        }
    }
#elif PI_AI_MIC_DOA_RING_OFFSET_180
    if (isfinite(azimuth)) {
        azimuth = fmodf(azimuth + (float)M_PI, PI_AI_MIC_TWO_PI);
        if (azimuth < 0.0f) {
            azimuth += PI_AI_MIC_TWO_PI;
        }
    }
#endif
    return azimuth;
}

#if PI_AI_MIC_DOA_RAW_RING_CODE_ENABLE
typedef struct {
    int i;
    int j;
    float delay_s;
    float confidence;
} pi_ai_mic_pair_delay_t;

static float pi_ai_mic_raw_corr_at_lag(const float *x,
                                       const float *y,
                                       float mean_x,
                                       float mean_y,
                                       int lag)
{
    int start = lag > 0 ? lag : 0;
    int end = lag < 0 ? (BECLEAR_SAMPLES_PER_FRAME + lag) : BECLEAR_SAMPLES_PER_FRAME;
    float sum = 0.0f;
    float energy_x = 0.0f;
    float energy_y = 0.0f;

    for (int n = start; n < end; n++) {
        float a = x[n] - mean_x;
        float b = y[n - lag] - mean_y;
        sum += a * b;
        energy_x += a * a;
        energy_y += b * b;
    }

    if (!(energy_x > 0.0f) || !(energy_y > 0.0f)) {
        return 0.0f;
    }

    return sum / sqrtf((energy_x * energy_y) + 1.0e-20f);
}

static pi_ai_mic_pair_delay_t pi_ai_mic_measure_pair_delay(float raw_mics[BECLEAR_NUMBER_OF_MICS][BECLEAR_SAMPLES_PER_FRAME],
                                                           const float means[BECLEAR_NUMBER_OF_MICS],
                                                           int i,
                                                           int j)
{
    pi_ai_mic_pair_delay_t pair = {
        .i = i,
        .j = j,
        .delay_s = 0.0f,
        .confidence = 0.0f,
    };

    for (int lag = -PI_AI_MIC_RAW_DOA_MAX_LAG_SAMPLES;
         lag <= PI_AI_MIC_RAW_DOA_MAX_LAG_SAMPLES;
         lag++) {
        float corr = pi_ai_mic_raw_corr_at_lag(raw_mics[i], raw_mics[j], means[i], means[j], lag);
#if PI_AI_MIC_RUNTIME_GEOMETRY_PROFILE_ENABLE
        float abs_corr = pi_ai_mic_raw_doa_abs_correlation() ? fabsf(corr) : corr;
#elif PI_AI_MIC_RAW_DOA_ABS_CORRELATION
        float abs_corr = fabsf(corr);
#else
        float abs_corr = corr;
#endif
        if (abs_corr > pair.confidence) {
            pair.confidence = abs_corr;
            pair.delay_s = (float)lag / (float)BECLEAR_SAMPLE_FREQUENCY;
        }
    }

    if (pair.confidence < 0.0f) {
        pair.confidence = 0.0f;
    }
    return pair;
}

static float pi_ai_mic_fit_raw_doa(const pi_ai_mic_pair_delay_t pairs[6],
                                   float *fit_error_s)
{
    /*
     * Position convention matches the raw validation tool. Absolute zero can be
     * rotated later at LED calibration time; the important part is stable angle
     * separation from the four raw PDM microphones.
     */
    static const float pcb_pos[BECLEAR_NUMBER_OF_MICS][2] = {
        { -0.0333f, -0.0333f },  /* D0: bottom-left, USB on left */
        { -0.0333f, 0.0333f },   /* D1: top-left */
        { 0.0333f, 0.0333f },    /* D2: top-right */
        { 0.0333f, -0.0333f },   /* D3: bottom-right */
    };
    static const float reference_pos[BECLEAR_NUMBER_OF_MICS][2] = {
        { 0.0333f, -0.0333f },
        { 0.0333f, 0.0333f },
        { -0.0333f, 0.0333f },
        { -0.0333f, -0.0333f },
    };
#if PI_AI_MIC_RUNTIME_GEOMETRY_PROFILE_ENABLE
    const float (*pos)[2] = pi_ai_mic_raw_doa_pcb_order() ? pcb_pos : reference_pos;
#elif PI_AI_MIC_RAW_DOA_PCB_ORDER
    const float (*pos)[2] = pcb_pos;
#else
    const float (*pos)[2] = reference_pos;
#endif
    float best_angle_rad = NAN;
    float best_score = 1.0e30f;
#if PI_AI_MIC_RUNTIME_GEOMETRY_PROFILE_ENABLE
    float delay_signs[2];
    unsigned delay_sign_count = 0;
    int configured_delay_sign = pi_ai_mic_raw_doa_delay_sign();
    if (configured_delay_sign > 0) {
        delay_signs[delay_sign_count++] = 1.0f;
    } else if (configured_delay_sign < 0) {
        delay_signs[delay_sign_count++] = -1.0f;
    } else {
        delay_signs[delay_sign_count++] = 1.0f;
        delay_signs[delay_sign_count++] = -1.0f;
    }
#else
    static const float delay_signs[] = {
#if PI_AI_MIC_RAW_DOA_DELAY_SIGN > 0
        1.0f
#elif PI_AI_MIC_RAW_DOA_DELAY_SIGN < 0
        -1.0f
#else
        1.0f, -1.0f
#endif
    };
#define PI_AI_MIC_DELAY_SIGN_COUNT (sizeof(delay_signs) / sizeof(delay_signs[0]))
#endif

    for (unsigned sign_i = 0;
#if PI_AI_MIC_RUNTIME_GEOMETRY_PROFILE_ENABLE
         sign_i < delay_sign_count;
#else
         sign_i < PI_AI_MIC_DELAY_SIGN_COUNT;
#endif
         sign_i++) {
        float sign = delay_signs[sign_i];

        for (int deg = 0; deg < 360; deg += 5) {
            float theta = (float)deg * ((float)M_PI / 180.0f);
            float dir_x = cosf(theta);
            float dir_y = sinf(theta);
            float arrivals[BECLEAR_NUMBER_OF_MICS];
            float weighted_error = 0.0f;
            float weight_sum = 0.0f;

            for (int mic = 0; mic < BECLEAR_NUMBER_OF_MICS; mic++) {
                arrivals[mic] = -((pos[mic][0] * dir_x) + (pos[mic][1] * dir_y)) /
                                PI_AI_MIC_RAW_DOA_SPEED_OF_SOUND;
            }

            for (int pair_i = 0; pair_i < 6; pair_i++) {
                const pi_ai_mic_pair_delay_t *pair = &pairs[pair_i];
                float predicted = arrivals[pair->i] - arrivals[pair->j];
                float measured = sign * pair->delay_s;
                float error = measured - predicted;
                float weight = pair->confidence;
                weighted_error += weight * error * error;
                weight_sum += weight;
            }

            if (weight_sum > 0.0f) {
                float score = weighted_error / weight_sum;
                if (score < best_score) {
                    best_score = score;
                    best_angle_rad = theta;
                }
            }
        }
    }

    if (fit_error_s != NULL) {
        *fit_error_s = sqrtf(best_score);
    }

    return best_angle_rad;
}

static float pi_ai_mic_raw_square_doa(float raw_mics[BECLEAR_NUMBER_OF_MICS][BECLEAR_SAMPLES_PER_FRAME],
                                      float *energy_out)
{
    float means[BECLEAR_NUMBER_OF_MICS] = {0.0f};
    float rms_sum = 0.0f;

    for (int mic = 0; mic < BECLEAR_NUMBER_OF_MICS; mic++) {
        float sum = 0.0f;
        for (int n = 0; n < BECLEAR_SAMPLES_PER_FRAME; n++) {
            sum += raw_mics[mic][n];
        }
        means[mic] = sum / (float)BECLEAR_SAMPLES_PER_FRAME;
    }

    for (int mic = 0; mic < BECLEAR_NUMBER_OF_MICS; mic++) {
        float energy = 0.0f;
        for (int n = 0; n < BECLEAR_SAMPLES_PER_FRAME; n++) {
            float sample = raw_mics[mic][n] - means[mic];
            energy += sample * sample;
        }
        rms_sum += sqrtf(energy / (float)BECLEAR_SAMPLES_PER_FRAME);
    }

    float rms = rms_sum / (float)BECLEAR_NUMBER_OF_MICS;
    if (energy_out != NULL) {
        *energy_out = rms;
    }
    if (!(rms > PI_AI_MIC_RAW_DOA_MIN_RMS)) {
        return NAN;
    }

    pi_ai_mic_pair_delay_t pairs[6];
    int pair_i = 0;
    float confidence_sum = 0.0f;
    for (int i = 0; i < BECLEAR_NUMBER_OF_MICS; i++) {
        for (int j = i + 1; j < BECLEAR_NUMBER_OF_MICS; j++) {
            pairs[pair_i] = pi_ai_mic_measure_pair_delay(raw_mics, means, i, j);
            confidence_sum += pairs[pair_i].confidence;
            pair_i++;
        }
    }

    float mean_confidence = confidence_sum / 6.0f;
    if (!(mean_confidence > PI_AI_MIC_RAW_DOA_MIN_CONFIDENCE)) {
        return NAN;
    }

    float fit_error_s = 0.0f;
    float angle = pi_ai_mic_fit_raw_doa(pairs, &fit_error_s);
    if (!isfinite(angle) || !(fit_error_s < PI_AI_MIC_RAW_DOA_MAX_FIT_ERROR_S)) {
        return NAN;
    }

    return angle;
}
#endif
#endif

/* *************************
 * Function declarations
 * *************************/


/* *************************
 * Static data
 * *************************/

static unsigned shf_out_buf_num = 0;
static shf_output_t shf_output_buf[NUM_SHF_OUTPUT_BUFFERS] = {{{{0}}}};

static int shf_runtime_mic_array_type(void)
{
#if PI_AI_MIC_FORCE_MIC_GEOMETRY_SQUARE
    return BECLEAR_CIRCULAR_ARRAY;
#elif PI_AI_MIC_FORCE_MIC_GEOMETRY_LINE
    return BECLEAR_LINEAR_ARRAY;
#elif PI_AI_MIC_BOARD
    return pi_ai_mic_get_mic_array_type();
#else
    return MIC_ARRAY_TYPE;
#endif
}

static unsigned shf_input_mic_index(unsigned dst_index)
{
#if PI_AI_MIC_SHF_MIC_REMAP_ENABLE
#if PI_AI_MIC_SHF_MIC_REMAP_SQUARE_ONLY && PI_AI_MIC_BOARD
    if (!pi_ai_mic_mic_geometry_cached_square()) {
        return dst_index;
    }
#endif
    static const unsigned map[BECLEAR_NUMBER_OF_MICS] = {
        PI_AI_MIC_SHF_MIC_REMAP_0,
        PI_AI_MIC_SHF_MIC_REMAP_1,
        PI_AI_MIC_SHF_MIC_REMAP_2,
        PI_AI_MIC_SHF_MIC_REMAP_3
    };
    unsigned src_index = map[dst_index];
    return (src_index < BECLEAR_NUMBER_OF_MICS) ? src_index : dst_index;
#else
    return dst_index;
#endif
}

/* *************************
 * function definitions
 * *************************/

void process_aec_control_command(control_pkt_t *pkt, aec_state_t* aec_state)
{
    static uint32_t far_mic_index[2] = {0};
    debug_printf("AEC Received %d command!!\n",pkt->cmd_id);
    uint8_t cmd = CONTROL_CMD_CLEAR_READ(pkt->cmd_id);
    if(SHF_Is_SHF_command_index(cmd))
    {
        if (IS_CONTROL_CMD_READ(pkt->cmd_id)) {
            SHF_GetPar_AEC(cmd, &pkt->payload[0]);
        }
        else {
            SHF_SetPar_AEC(cmd, &pkt->payload[0]);
        }
    }
    else
    {
        if (IS_CONTROL_CMD_READ(pkt->cmd_id))
        {
            switch(cmd) {
            case AEC_RESID_SPECIAL_CMD_AEC_FILTER_LENGTH:
            {
                uint32_t filter_len = SHF_AEC_LENGTH * SHF_NUM_BANDS;
                memcpy(pkt->payload, &filter_len, sizeof(uint32_t));
            }
            break;
            case AEC_RESID_SPECIAL_CMD_AEC_FILTER_COEFFS:
            {
                SHF_GetAECCoefs_AEC(far_mic_index[0], far_mic_index[1], pkt->payload_len, (float*)pkt->payload);
            }
            break;
            case AEC_RESID_AEC_NUM_MICS:
            {
                *((int32_t*)pkt->payload) = BECLEAR_NUMBER_OF_MICS;
            }
            break;
            case AEC_RESID_AEC_NUM_FARENDS:
            {
                *((int32_t*)pkt->payload) = BECLEAR_MAX_NUMBER_OF_FARENDS;
            }
            break;
            case AEC_RESID_AEC_MIC_ARRAY_TYPE:
            {
                *((int32_t*)pkt->payload) = shf_runtime_mic_array_type();
            }
            break;
            case AEC_RESID_AEC_MIC_ARRAY_GEO:
            {
                for (int mic_i =0 ; mic_i < BECLEAR_NUMBER_OF_MICS; mic_i++) {
                    memcpy(pkt->payload + mic_i * sizeof(float)*3, aec_state->micpos[mic_i], sizeof(float)*3);
                }
            }
            break;
            case AEC_RESID_AEC_AZIMUTH_VALUES:
            {
                float spenergy[BECLEAR_NUMBER_OF_OUTPUTS];
                SHF_Get_azimuths(pkt->payload, spenergy, AEC_RESID_AEC_AZIMUTH_VALUES_NUM_VALUES);
            }
            break;
            case AEC_RESID_AEC_SPENERGY_VALUES:
            {
                float azimuths[BECLEAR_NUMBER_OF_OUTPUTS];
                SHF_Get_azimuths(azimuths, pkt->payload, AEC_RESID_AEC_SPENERGY_VALUES_NUM_VALUES);
            }
            break;
// RESID_X_NUM_VALUES is a macro, but RESID_X is an enum member so can't #ifdef
#ifdef AEC_RESID_AEC_FIXEDBEAMSAZIMUTH_VALUES_NUM_VALUES
            case AEC_RESID_AEC_FIXEDBEAMSAZIMUTH_VALUES:
            {
                float elevation[BECLEAR_NUMBER_OF_BEAMS];
                SHF_Get_fixed_beams_azimuths(pkt->payload, elevation, AEC_RESID_AEC_FIXEDBEAMSAZIMUTH_VALUES_NUM_VALUES);
            }
            break;
#endif
#ifdef AEC_RESID_AEC_FIXEDBEAMSELEVATION_VALUES_NUM_VALUES
            case AEC_RESID_AEC_FIXEDBEAMSELEVATION_VALUES:
            {
                float azimuths[BECLEAR_NUMBER_OF_BEAMS];
                SHF_Get_fixed_beams_azimuths(azimuths, pkt->payload, AEC_RESID_AEC_FIXEDBEAMSELEVATION_VALUES_NUM_VALUES);
            }
            break;
#endif
#ifdef AEC_RESID_AEC_FIXEDBEAMSGATING_NUM_VALUES
            case AEC_RESID_AEC_FIXEDBEAMSGATING:
            {
                memcpy(pkt->payload, &aec_state->fixed_beams_gated, sizeof(aec_state->fixed_beams_gated));
            }
            break;
#endif
            case AEC_RESID_SHF_BYPASS:
            {
                memcpy(pkt->payload, &aec_state->bypass, sizeof(aec_state->bypass));
            }
            break;
            case AEC_RESID_AEC_CURRENT_IDLE_TIME:
            {
                memcpy(pkt->payload, &aec_state->idle_time_ticks, sizeof(aec_state->idle_time_ticks));
            }
            break;
            case AEC_RESID_AEC_MIN_IDLE_TIME:
            {
                memcpy(pkt->payload, &aec_state->min_idle_time_ticks, sizeof(aec_state->min_idle_time_ticks));
            }
            break;
            default:
            {
                xassert(0);
            }
            break;
            }
        }
        else
        {
            switch(cmd) {
            case AEC_RESID_SPECIAL_CMD_AEC_FAR_MIC_INDEX:
            {
                memcpy(far_mic_index, pkt->payload, pkt->payload_len);
            }
            break;
            case AEC_RESID_SPECIAL_CMD_AEC_FILTER_COEFFS:
            {
                SHF_SetAECCoefs_AEC(far_mic_index[0], far_mic_index[1], pkt->payload_len, (float*)pkt->payload);
            }
            break;
            case AEC_RESID_SHF_BYPASS:
            {
                memcpy(&aec_state->bypass, pkt->payload, sizeof(aec_state->bypass));

                SHF_Sync_bypass_with_remote((int8_t)aec_state->bypass); // Sync with remote
            }
            break;
            case AEC_RESID_AEC_RESET_MIN_IDLE_TIME:
            {
                aec_state->min_idle_time_ticks = SHF_FRAME_TIME_TICKS;
            }
            break;
// RESID_X_NUM_VALUES is a macro, but RESID_X is an enum member so can't #ifdef
#ifdef AEC_RESID_AEC_FIXEDBEAMSAZIMUTH_VALUES_NUM_VALUES
            case AEC_RESID_AEC_FIXEDBEAMSAZIMUTH_VALUES:
            {
                float azimuths[BECLEAR_NUMBER_OF_BEAMS];
                float elevation[BECLEAR_NUMBER_OF_BEAMS];
                // Read the current elevation angles, as we need to set azimuth and elevation values at the same time
                SHF_Get_fixed_beams_azimuths(azimuths, elevation, BECLEAR_NUMBER_OF_BEAMS);
                SHF_Set_fixed_beams_azimuths(pkt->payload, elevation, BECLEAR_NUMBER_OF_BEAMS);
            }
            break;
#endif
#ifdef AEC_RESID_AEC_FIXEDBEAMSELEVATION_VALUES_NUM_VALUES
            case AEC_RESID_AEC_FIXEDBEAMSELEVATION_VALUES:
            {
                float azimuths[BECLEAR_NUMBER_OF_BEAMS];
                float elevation[BECLEAR_NUMBER_OF_BEAMS];
                // Read the current azimuths, as we need to set azimuth and elevation values at the same time
                SHF_Get_fixed_beams_azimuths(azimuths, elevation, BECLEAR_NUMBER_OF_BEAMS);
                SHF_Set_fixed_beams_azimuths(azimuths, pkt->payload, BECLEAR_NUMBER_OF_BEAMS);
            }
            break;
#endif
#ifdef AEC_RESID_AEC_FIXEDBEAMSGATING_NUM_VALUES
            case AEC_RESID_AEC_FIXEDBEAMSGATING:
            {
                memcpy(&aec_state->fixed_beams_gated, pkt->payload, sizeof(aec_state->fixed_beams_gated));
            }
            break;
#endif
            default:
            {
                xassert(0);
            }
            break;
            }
        }
    }
}

void process_pp_control_command(control_pkt_t *pkt, pp_state_t * pp_state)
{
    static uint8_t nlmodel_band_index = 0;

    debug_printf("PP Received %d command!!\n",pkt->cmd_id);
    uint8_t cmd = CONTROL_CMD_CLEAR_READ(pkt->cmd_id);
    if(SHF_Is_SHF_command_index(cmd))
    {
        if (IS_CONTROL_CMD_READ(pkt->cmd_id)) {
            SHF_GetPar_PP(cmd, &pkt->payload[0]);
        }
        else {
            SHF_SetPar_PP(cmd, &pkt->payload[0]);
        }
    }
    else
    {
        if (IS_CONTROL_CMD_READ(pkt->cmd_id))
        {
            if (cmd == PP_RESID_SPECIAL_CMD_PP_NLMODEL_NROW_NCOL)
            {
                size_t NRowCol[2];

                SHF_GetNLModelSize_PP(nlmodel_band_index, &NRowCol[0], &NRowCol[1]);

                xassert(NRowCol[0] <= MAX_NL_MODEL_ROWS);
                xassert(NRowCol[1] <= MAX_NL_MODEL_COLS);
                memcpy(pkt->payload, &NRowCol[0], pkt->payload_len);
            }
            else if (cmd == PP_RESID_SPECIAL_CMD_PP_NLMODEL)
            {
                SHF_Get_NLmodel(nlmodel_band_index, (float*)pkt->payload);
            }
            else if (cmd == PP_RESID_PP_CURRENT_IDLE_TIME)
            {
                memcpy(pkt->payload, &pp_state->idle_time_ticks, sizeof(pp_state->idle_time_ticks));
            }
            else if (cmd == PP_RESID_PP_MIN_IDLE_TIME)
            {
                memcpy(pkt->payload, &pp_state->min_idle_time_ticks, sizeof(pp_state->min_idle_time_ticks));
            }
            else if (cmd == PP_RESID_SPECIAL_CMD_PP_NLMODEL_BAND)
            {
                *((uint8_t*)pkt->payload) = nlmodel_band_index;
            }
            else if (cmd == PP_RESID_SPECIAL_CMD_PP_EQUALIZATION_NUM_BANDS)
            {
                SHF_Get_EQNbands(pkt->payload);
            }
            else if (cmd == PP_RESID_SPECIAL_CMD_PP_EQUALIZATION)
            {
                SHF_Get_EQ((float*)pkt->payload);
            }
            else
            {
                xassert(0);
            }
        }
        else // is a write
        {
            if (cmd == PP_RESID_SPECIAL_CMD_PP_NLMODEL)
            {
                SHF_Set_NLmodel(nlmodel_band_index, (float*)pkt->payload);

            }
            else if (cmd == PP_RESID_PP_RESET_MIN_IDLE_TIME)
            {
                pp_state->min_idle_time_ticks = SHF_FRAME_TIME_TICKS;
            }
            else if (cmd == PP_RESID_SPECIAL_CMD_PP_NLMODEL_BAND)
            {
                nlmodel_band_index = *((uint8_t*)pkt->payload);
            }
            else if (cmd == PP_RESID_SPECIAL_CMD_PP_EQUALIZATION)
            {
                SHF_Set_EQ((float*)pkt->payload);
            }
            else
            {
                xassert(0);
            }
        }
    }
}

void do_aec_control(control_pkt_queue_t *pkt_queue, aec_state_t* aec_state)
{
    static uint32_t disable_control = 0;
    if(disable_control)
    {
        return;
    }

    int32_t num_pkts_processed = 0;
    do
    {
        control_pkt_t *pkt = queue_read_packet(pkt_queue);
        /* code */
        if (pkt != NULL)
        {
            if(pkt->cmd_id == AEC_RESID_TEST_AEC_DISABLE_CONTROL)
            {
                memcpy(&disable_control, pkt->payload, pkt->payload_len);
            }
            else
            {
                debug_printf("SHF do control: processing packet\n");
                process_aec_control_command(pkt, aec_state);
            }

            // Change status to done at the end
            pkt->pkt_status = PKT_DONE;
            pkt_queue->queue_rd_index = (pkt_queue->queue_rd_index + 1) % pkt_queue->depth;
            num_pkts_processed++;
        }
        else {
            break;
        }
    } while (num_pkts_processed != pkt_queue->depth); // We don't process more than the full queue depth

    SHF_Signal_control_done_to_remote_AEC();
}

void do_pp_control(control_pkt_queue_t *pkt_queue, pp_state_t * pp_state)
{
    int32_t num_pkts_processed = 0;
    do
    {
        control_pkt_t *pkt = queue_read_packet(pkt_queue);
        /* code */
        if (pkt != NULL)
        {
            debug_printf("SHF do control: processing packet\n");
            process_pp_control_command(pkt, pp_state);

            // Change status to done at the end
            pkt->pkt_status = PKT_DONE;
            pkt_queue->queue_rd_index = (pkt_queue->queue_rd_index + 1) % pkt_queue->depth;
            num_pkts_processed++;
        }
        else {
            break;
        }
    } while (num_pkts_processed != pkt_queue->depth); // We don't process more than the full queue depth

    SHF_Signal_control_done_to_remote_PP();
}

void bypass_loop(control_pkt_queue_t* ctl_q, chanend_t c_to_aec, pp_state_t * pp_state_p) {
    // buf on the stack so it can reuse the memory that shf uses, note writing
    // 0 to 2kB buff might take some time and it will happen every time bypass is
    // enabled
    float buf[BECLEAR_MAX_NUMBER_OF_MICS][BECLEAR_SAMPLES_PER_FRAME] = {{0}};

    unsigned count = 0; // For debug display message only
    bool bypass = 1;
    uint32_t t0 = get_reference_time();
    do {
        // main follows in_word, matching aec_task
        shf_bypass_main_pp(get_core_burn_status(), buf);

        do_pp_control(ctl_q, pp_state_p);
        count++;
        if(count == 200){
            debug_printf("PP - %d %d\n", pp_state_p->idle_time_ticks, pp_state_p->min_idle_time_ticks);
            count = 0;
        }
        uint32_t pp_exec_time_ticks = get_reference_time() - t0;
        pp_state_p->idle_time_ticks = SHF_FRAME_TIME_TICKS - pp_exec_time_ticks;
        pp_state_p->min_idle_time_ticks = pp_state_p->idle_time_ticks < pp_state_p->min_idle_time_ticks ? pp_state_p->idle_time_ticks : pp_state_p->min_idle_time_ticks;

        bypass = chan_in_word(c_to_aec);

        t0 = get_reference_time();

    } while(bypass);
}

void pp_loop(control_pkt_queue_t* ctl_q, chanend_t c_to_aec, pp_state_t * pp_state_p) {
    unsigned count = 0; // For debug display message only
    bool bypass = 0;
    uint32_t t0 = get_reference_time();
    do {
        // main follows in_word, matching aec_task
        SHF_Main_PP();

        do_pp_control(ctl_q, pp_state_p);
        count++;
        if(count == 200){
            debug_printf("PP - %d %d\n", pp_state_p->idle_time_ticks, pp_state_p->min_idle_time_ticks);
            count = 0;
        }
        uint32_t pp_exec_time_ticks = get_reference_time() - t0;
        pp_state_p->idle_time_ticks = SHF_FRAME_TIME_TICKS - pp_exec_time_ticks;
        pp_state_p->min_idle_time_ticks = pp_state_p->idle_time_ticks < pp_state_p->min_idle_time_ticks ? pp_state_p->idle_time_ticks : pp_state_p->min_idle_time_ticks;

        bypass = chan_in_word(c_to_aec);

        t0 = get_reference_time();
    } while(!bypass);
}

void init_pp_state(pp_state_t * pp_state_p) {

    pp_state_p->min_idle_time_ticks = SHF_FRAME_TIME_TICKS;
    pp_state_p->idle_time_ticks = SHF_FRAME_TIME_TICKS;
}

DEFINE_INTERRUPT_PERMITTED (SETUP_PKT_RECV_INTERRUPTABLE_FUNCTIONS, void, pp_task, chanend_t* shf_pp_chanends, control_pkt_queue_t *control_pkt_queue)
{
    SETSR(XS1_SR_QUEUE_MASK);

    chanend_t c_aec_to_pp = shf_pp_chanends[0];

    void * mem = SHF_GetMemory_PP();

    SHF_Init_PP_split_post(
        mem,
        shf_pp_chanends);

    init_pp_parameters();

    pp_state_t pp_state;
    init_pp_state(&pp_state);

    shf_bypass_init_pp(c_aec_to_pp);

    // from here we split to do shf or bypass. bypass on this thread
    // has a large buffer which is kept on the stack and must persist
    // between frames of data. Therefore pp_loop and bypass loop each
    // contain a loop which loops until bypass state changes.
    bool bypass = chan_in_word(c_aec_to_pp);
    while(1){
        if(!bypass) {
            pp_loop(control_pkt_queue, c_aec_to_pp, &pp_state);
            bypass_loop(control_pkt_queue, c_aec_to_pp, &pp_state);
        } else {
            bypass_loop(control_pkt_queue, c_aec_to_pp, &pp_state);
            pp_loop(control_pkt_queue, c_aec_to_pp, &pp_state);
        }
    }
}


void init_aec_state(aec_state_t * aec_state_p) {

    aec_state_p->micpos[0] = shf_defaults_get_mic_geo()->mic0;
    aec_state_p->micpos[1] = shf_defaults_get_mic_geo()->mic1;
    aec_state_p->micpos[2] = shf_defaults_get_mic_geo()->mic2;
    aec_state_p->micpos[3] = shf_defaults_get_mic_geo()->mic3;

    aec_state_p->bypass = false;

    aec_state_p->min_idle_time_ticks = SHF_FRAME_TIME_TICKS;
    aec_state_p->idle_time_ticks = SHF_FRAME_TIME_TICKS;

    aec_state_p->fixed_beams_gated = false;
}

void aec_task(chanend_t* aec_channels, chanend_t c_audio_to_aec, control_pkt_queue_t *control_pkt_queue){
    SETSR(XS1_SR_QUEUE_MASK);

    chanend_t c_aec_to_pp = aec_channels[0];

    uint32_t aec_exec_time_ticks = 0;

    aec_state_t aec_state;

    doa_smoothing_t doa_ctx = DOA_SMOOTHING_INITIALISER;

#if (FIXED_BEAMS_ENABLED == 1)
    gate_vad_state_t gate_ctx = GATE_VAD_INITIALISER;
#endif

#if PI_AI_MIC_BOARD
    /*
     * user_init_hardware() runs in the RTOS IO config task, while AEC is a
     * bare-metal task in this PAR block. Wait here so BeClear sees the P6
     * square/line geometry strap at init.
     */
    pi_ai_mic_wait_for_mic_geometry_ready();
#endif

    init_aec_state(&aec_state);

    // Debug
    unsigned count = 0; // For debug display message only
    uint32_t t0 = get_reference_time();

    void * mem = SHF_GetMemory_AEC();

    SHF_Init_AEC_split_post(
        mem,
        aec_state.micpos,
        shf_runtime_mic_array_type(),
        aec_channels);

    init_aec_parameters();

    // using the same channel for both should be fine as in the
    // example for SHF they use the same channel to synchronise
    // the threads between calls to Main. We are doing the same
    // thing.
    shf_bypass_init_aec(c_aec_to_pp);

    while(1){
        do_aec_control(control_pkt_queue, &aec_state);

        // Check execution time of AEC loop including buffer exchange
        aec_exec_time_ticks = get_reference_time() - t0;
        aec_state.idle_time_ticks = SHF_FRAME_TIME_TICKS - aec_exec_time_ticks;
        aec_state.min_idle_time_ticks = aec_state.idle_time_ticks < aec_state.min_idle_time_ticks ? aec_state.idle_time_ticks : aec_state.min_idle_time_ticks;


        // Exchange buffers with audio. This has been measured at around 12 ticks = 120ns
        shf_input_t *shf_input = (shf_input_t *)(uintptr_t)chan_in_word(c_audio_to_aec);
        t0 = get_reference_time();
        uint32_t addr_of_shf_output = (uint32_t)(uintptr_t)(&shf_output_buf[shf_out_buf_num]);
        chan_out_word(c_audio_to_aec, addr_of_shf_output);

        // Flip output buffer if double, else do nothing
        shf_out_buf_num ^= (NUM_SHF_OUTPUT_BUFFERS - 1);
        shf_output_t* this_output_buf = &shf_output_buf[shf_out_buf_num];

        // prepare inputs
        float* mics[BECLEAR_NUMBER_OF_MICS];
        float* spks[BECLEAR_NUMBER_OF_FAR];
        float* qcom[BECLEAR_NUMBER_OF_OUTPUTS];
        float* aecmics[BECLEAR_NUMBER_OF_MICS];
        for(int i = 0; i < BECLEAR_NUMBER_OF_MICS; ++i) {
            unsigned src_i = shf_input_mic_index(i);
            mics[i] = &shf_input->mics[src_i][0];
             // SHF supports overwriting the mic input with the AEC residuals in-place.
             // We take advantage of this to save creating another 4ch*4byte*256sample*2buffer = 8KiB buffer.
            aecmics[i] = &shf_input->mics[src_i][0];
        }
        for(int i = 0; i < BECLEAR_NUMBER_OF_OUTPUTS; ++i) {
            qcom[i] = &this_output_buf->commsout[i][0];
        }
        for(int i = 0; i < BECLEAR_NUMBER_OF_FAR; ++i) {
            spks[i] = &shf_input->far[i][0];
        }

#if PI_AI_MIC_DOA_NEOPIXEL_ENABLE && PI_AI_MIC_DOA_RAW_RING_CODE_ENABLE
        float pi_ai_mic_raw_ring_energy = 0.0f;
        float pi_ai_mic_raw_ring_azimuth = NAN;
#if PI_AI_MIC_RUNTIME_GEOMETRY_PROFILE_ENABLE
        if (pi_ai_mic_doa_raw_ring_enabled()) {
            pi_ai_mic_raw_ring_azimuth = pi_ai_mic_raw_square_doa(shf_input->mics, &pi_ai_mic_raw_ring_energy);
        }
#elif PI_AI_MIC_FORCE_MIC_GEOMETRY_SQUARE
        pi_ai_mic_raw_ring_azimuth = pi_ai_mic_raw_square_doa(shf_input->mics, &pi_ai_mic_raw_ring_energy);
#elif PI_AI_MIC_BOARD
        if (pi_ai_mic_mic_geometry_cached_square()) {
            pi_ai_mic_raw_ring_azimuth = pi_ai_mic_raw_square_doa(shf_input->mics, &pi_ai_mic_raw_ring_energy);
        }
#else
        pi_ai_mic_raw_ring_azimuth = pi_ai_mic_raw_square_doa(shf_input->mics, &pi_ai_mic_raw_ring_energy);
#endif
#endif

        chan_out_word(c_aec_to_pp, aec_state.bypass);
        if(!aec_state.bypass) {
            SHF_Main_AEC(
                mics,
                spks,
                qcom,
                aecmics
            );
            SHF_Get_azimuths(this_output_buf->azimuths, this_output_buf->spenergy, AEC_RESID_AEC_AZIMUTH_VALUES_NUM_VALUES);
            this_output_buf->smoothed_azimuth = doa_smoothing(&doa_ctx, this_output_buf->azimuths, this_output_buf->spenergy);
#if PI_AI_MIC_DOA_NEOPIXEL_ENABLE
#if AEC_RESID_AEC_AZIMUTH_VALUES_NUM_VALUES > PI_AI_MIC_DOA_AUTO_SELECTED_INDEX
#if PI_AI_MIC_DOA_RAW_RING_CODE_ENABLE
#if PI_AI_MIC_RUNTIME_GEOMETRY_PROFILE_ENABLE
            if (pi_ai_mic_doa_raw_ring_enabled()) {
#endif
            this_output_buf->smoothed_azimuth = pi_ai_mic_doa_ring_select(
                NAN,
                pi_ai_mic_raw_ring_azimuth);
            this_output_buf->smoothed_azimuth =
                pi_ai_mic_doa_apply_ring_offset(this_output_buf->smoothed_azimuth);
            pi_ai_mic_neopixel_publish_doa(
                this_output_buf->smoothed_azimuth,
                isfinite(pi_ai_mic_raw_ring_azimuth) ? pi_ai_mic_raw_ring_energy : 0.0f);
#if PI_AI_MIC_RUNTIME_GEOMETRY_PROFILE_ENABLE
            } else {
                this_output_buf->smoothed_azimuth = pi_ai_mic_doa_ring_select(
                    this_output_buf->smoothed_azimuth,
                    this_output_buf->azimuths[PI_AI_MIC_DOA_AUTO_SELECTED_INDEX]);
                this_output_buf->smoothed_azimuth =
                    pi_ai_mic_doa_apply_ring_offset(this_output_buf->smoothed_azimuth);
                pi_ai_mic_neopixel_publish_doa(
                    this_output_buf->smoothed_azimuth,
                    this_output_buf->spenergy[PI_AI_MIC_DOA_AUTO_SELECTED_INDEX]);
            }
#endif
#else
            this_output_buf->smoothed_azimuth = pi_ai_mic_doa_ring_select(
                this_output_buf->smoothed_azimuth,
                this_output_buf->azimuths[PI_AI_MIC_DOA_AUTO_SELECTED_INDEX]);
            this_output_buf->smoothed_azimuth =
                pi_ai_mic_doa_apply_ring_offset(this_output_buf->smoothed_azimuth);
            pi_ai_mic_neopixel_publish_doa(
                this_output_buf->smoothed_azimuth,
                this_output_buf->spenergy[PI_AI_MIC_DOA_AUTO_SELECTED_INDEX]);
#endif
#endif
#endif
#if (FIXED_BEAMS_ENABLED == 1)
            if (aec_state.fixed_beams_gated)
            {
                fixed_beam_gating(&gate_ctx, BECLEAR_SAMPLES_PER_FRAME, qcom, this_output_buf->spenergy);
            }
#endif
        }
        else {
            shf_bypass_main_aec(
                mics,
                spks,
                qcom,
                aecmics,
                get_core_burn_status()
            );
            memset(this_output_buf->azimuths, 0, sizeof(this_output_buf->azimuths));
            memset(this_output_buf->spenergy, 0, sizeof(this_output_buf->spenergy));
            this_output_buf->smoothed_azimuth = NAN;
        }

        for(int i = 0; i < BECLEAR_NUMBER_OF_OUTPUTS; ++i) {
            for(int j = 0; j < BECLEAR_SAMPLES_PER_FRAME; ++j) {
#if PI_AI_MIC_PROCESSED_USB_GAIN_Q8 != 256
                qcom[i][j] = (qcom[i][j] * (float)PI_AI_MIC_PROCESSED_USB_GAIN_Q8) / 256.0f;
#endif
                qcom[i][j] = MAX(qcom[i][j], BECLEAR_MIN_SAMPLE);
                qcom[i][j] = MIN(qcom[i][j], BECLEAR_MAX_SAMPLE);
                aecmics[i][j] = MAX(aecmics[i][j], BECLEAR_MIN_SAMPLE);
                aecmics[i][j] = MIN(aecmics[i][j], BECLEAR_MAX_SAMPLE);
            }
        }

        count++;
        if(count == 200){
            debug_printf("AEC - %d %d\n", aec_state.idle_time_ticks, aec_state.min_idle_time_ticks);
            count = 0;
        }
    }
}
